# Generated by Django 4.1.3 on 2022-11-29 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ToDoApp', '0002_todo_alter_search_search'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='task_name',
            new_name='task',
        ),
    ]
